# http://www.appveyor.com/docs/appveyor-yml

version: "{build}"

clone_depth: 10

install:
  - SET PATH=C:\Ruby%ruby_folder_version%\bin;%PATH%
  - gem install jekyll --no-rdoc --no-ri
  - npm install -g grunt-cli
  - npm install
  - bundle install --clean --retry 3

build: off

test_script:
  - ruby -v && gem -v && node -v && npm -v
  - npm test

cache:
  - C:\Users\appveyor\.gem -> Gemfile,Gemfile.lock
  - C:\Ruby%ruby_folder_version%\bin -> Gemfile,Gemfile.lock
  - C:\Ruby%ruby_folder_version%\lib\ruby\gems\%ruby_gems_folder% -> Gemfile,Gemfile.lock
  - C:\Users\appveyor\AppData\Roaming\npm\node_modules
  - node_modules

environment:
  matrix:
    - ruby_folder_version: "193"
      ruby_gems_folder: "1.9.1"
    - ruby_folder_version: "200"
      ruby_gems_folder: "2.0.0"
    - ruby_folder_version: "200-x64"
      ruby_gems_folder: "2.0.0"
    - ruby_folder_version: "21"
      ruby_gems_folder: "2.1.0"
    - ruby_folder_version: "21-x64"
      ruby_gems_folder: "2.1.0"

matrix:
  fast_finish: true
